apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    azurekv:
      vaultUrl: "https://{{ .Values.global.keyVaultName }}.vault.azure.net"
      tenantId: {{ .Values.global.tenantId }}
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets-system
