apiVersion: v1
kind: Secret
metadata:
  name: iot-credentials
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  GRAFANA_ADMIN_USER: ${GRAFANA_ADMIN_USER}
  GRAFANA_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}