{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grafana
    chart: {{ include "iot-stack-chart.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: grafana
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 472  # Grafana user group
        runAsUser: 472  # Grafana user ID
      initContainers:
      - name: grafana-permissions
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - |
            chown -R 472:472 /var/lib/grafana
            chmod -R 755 /var/lib/grafana
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        securityContext:
          runAsUser: 0  # Run as root to fix permissions
      containers:
      - name: grafana
        image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
        imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.grafana.service.port }}
        envFrom:
        - secretRef:
            name: iot-secrets
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        resources:
          {{- toYaml .Values.grafana.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.grafana.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grafana
    chart: {{ include "iot-stack-chart.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: {{ .Values.grafana.service.port }}
    protocol: TCP
    name: http
  selector:
    app: grafana
    release: {{ .Release.Name }}
{{- end }}