---
# base.yml - Base system setup for IoT infrastructure
- name: Configure base system requirements for IoT services
  hosts: iot_servers
  tasks:
    # --------------------------------------------------------------------------
    # Wait for System Readiness
    # --------------------------------------------------------------------------
    - name: Wait for apt/dpkg locks to be released
      ansible.builtin.shell: while lsof /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done
      changed_when: false
      timeout: 300  # 5 minute timeout

    - name: Wait for cloud-init to complete
      ansible.builtin.shell: while [ ! -f /var/lib/cloud/instance/boot-finished ]; do sleep 5; done
      changed_when: false
      timeout: 300  # 5 minute timeout

    # --------------------------------------------------------------------------
    # Docker Installation
    # --------------------------------------------------------------------------
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Install required dependencies for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      become: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker # Explicit filename
      become: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes
      register: docker_install_result
      until: docker_install_result is succeeded
      retries: 5
      delay: 15
      become: yes

    - name: Make sure Docker service is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add deployment user to docker group for non-sudo docker commands
      ansible.builtin.user:
        name: "{{ ansible_user | default('nathan') }}" # Use ansible_user which is 'nathan' from ansible.cfg
        groups: docker
        append: yes
      become: yes
      
    # --------------------------------------------------------------------------
    # Set up Docker network
    # --------------------------------------------------------------------------
    - name: Set up Docker network for IoT services
      community.docker.docker_network:
        name: iot_network
        state: present
      become: yes
      
    # --------------------------------------------------------------------------
    # Install common tools
    # --------------------------------------------------------------------------
    - name: Install common tools and utilities
      ansible.builtin.apt:
        name:
          - htop
          - tmux
          - vim
          - curl
          - wget
          - net-tools
          - postgresql-client  # For database connectivity testing
        state: present
      become: yes