apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: ${NAMESPACE}
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data
    log_dest stdout
    log_type all
    listener 1883
    allow_anonymous true