apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: ${NAMESPACE}
  labels:
    app: timescaledb
    component: database
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: timescaledb